<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // Fruit Juices - lowercase with hyphens
            [
                'id' => 1,
                'name' => 'Orange Juice 300ml',
                'category' => 'juices',
                'description' => 'Freshly squeezed orange juice, rich in vitamin C and natural flavors.',
                'price' => 250.00,
                'stock' => 50,
                'image' => 'images/Fruit Juices/orange-juice.png',
            ],
            [
                'id' => 2,
                'name' => 'Apple Juice 300ml',
                'category' => 'juices',
                'description' => 'Crisp and refreshing apple juice made from premium apples.',
                'price' => 240.00,
                'stock' => 45,
                'image' => 'images/Fruit Juices/apple-juice.png',
            ],
            [
                'id' => 3,
                'name' => 'Pineapple Juice 300ml',
                'category' => 'juices',
                'description' => 'Tropical pineapple juice with sweet and tangy flavors.',
                'price' => 260.00,
                'stock' => 40,
                'image' => 'images/Fruit Juices/pineapple-juice.png',
            ],
            [
                'id' => 4,
                'name' => 'Mango Juice 300ml',
                'category' => 'juices',
                'description' => 'Creamy mango juice with tropical sweetness and smooth texture.',
                'price' => 280.00,
                'stock' => 35,
                'image' => 'images/Fruit Juices/mango-juice.png',
            ],
            [
                'id' => 5,
                'name' => 'Grape Juice 300ml',
                'category' => 'juices',
                'description' => 'Nutritious grape juice packed with vitamins and antioxidants.',
                'price' => 270.00,
                'stock' => 30,
                'image' => 'images/Fruit Juices/grape-juice.png',
            ],
            [
                'id' => 6,
                'name' => 'Papaya Juice 300ml',
                'category' => 'juices',
                'description' => 'Digestive-friendly papaya juice with natural enzymes.',
                'price' => 275.00,
                'stock' => 32,
                'image' => 'images/Fruit Juices/papaya-juice.png',
            ],
            [
                'id' => 7,
                'name' => 'Watermelon Juice 300ml',
                'category' => 'juices',
                'description' => 'Refreshing watermelon juice perfect for hot summer days.',
                'price' => 265.00,
                'stock' => 42,
                'image' => 'images/Fruit Juices/watermelon-juice.png',
            ],
            [
                'id' => 8,
                'name' => 'Lime Juice 300ml',
                'category' => 'juices',
                'description' => 'Zesty lime juice with a tangy and refreshing taste.',
                'price' => 255.00,
                'stock' => 38,
                'image' => 'images/Fruit Juices/lime-juice.png',
            ],
            [
                'id' => 9,
                'name' => 'Mixed Fruit Juice 300ml',
                'category' => 'juices',
                'description' => 'Blend of seasonal fruits for a balanced and nutritious drink.',
                'price' => 285.00,
                'stock' => 36,
                'image' => 'images/Fruit Juices/mixed-fruit-juice.png',
            ],
            [
                'id' => 10,
                'name' => 'Woodapple Juice 300ml',
                'category' => 'juices',
                'description' => 'Sweet woodapple juice with vibrant red color and berry flavor.',
                'price' => 290.00,
                'stock' => 30,
                'image' => 'images/Fruit Juices/woodapple-juice.png',
            ],

            // Soft Drinks - lowercase with hyphens
            [
                'id' => 11,
                'name' => 'Cola Classic 330ml',
                'category' => 'soft-drinks',
                'description' => 'Classic cola with iconic carbonated bubbles and caffeine kick.',
                'price' => 180.00,
                'stock' => 100,
                'image' => 'images/Soft Drinks/cola-classic.png',
            ],
            [
                'id' => 12,
                'name' => 'Lemon Soda 330ml',
                'category' => 'soft-drinks',
                'description' => 'Citrusy lemon soda with zesty flavor and fizzy bubbles.',
                'price' => 175.00,
                'stock' => 95,
                'image' => 'images/Soft Drinks/lemon-soda.png',
            ],
            [
                'id' => 13,
                'name' => 'Orange Soda 330ml',
                'category' => 'soft-drinks',
                'description' => 'Artificial orange soda with bright citrus flavor and carbonation.',
                'price' => 170.00,
                'stock' => 90,
                'image' => 'images/Soft Drinks/orange-soda.png',
            ],
            [
                'id' => 14,
                'name' => 'Ginger Ale 330ml',
                'category' => 'soft-drinks',
                'description' => 'Spicy ginger ale with natural ginger flavor and smooth finish.',
                'price' => 185.00,
                'stock' => 85,
                'image' => 'images/Soft Drinks/ginger-ale.png',
            ],
            [
                'id' => 15,
                'name' => 'Root Beer 330ml',
                'category' => 'soft-drinks',
                'description' => 'Creamy root beer with vanilla and spice notes.',
                'price' => 190.00,
                'stock' => 80,
                'image' => 'images/Soft Drinks/root-beer.png',
            ],
            [
                'id' => 16,
                'name' => 'Grape Soda 330ml',
                'category' => 'soft-drinks',
                'description' => 'Purple grape soda with sweet berry flavors and carbonation.',
                'price' => 175.00,
                'stock' => 88,
                'image' => 'images/Soft Drinks/grape-soda.png',
            ],
            [
                'id' => 17,
                'name' => 'Lime Soda 330ml',
                'category' => 'soft-drinks',
                'description' => 'Tart lime soda with refreshing citrus burst.',
                'price' => 170.00,
                'stock' => 92,
                'image' => 'images/Soft Drinks/lime-soda.png',
            ],
            [
                'id' => 18,
                'name' => 'Pineapple Soda 330ml',
                'category' => 'soft-drinks',
                'description' => 'Tropical pineapple soda with sweet and tangy flavor.',
                'price' => 180.00,
                'stock' => 87,
                'image' => 'images/Soft Drinks/pineapple-soda.png',
            ],
            [
                'id' => 19,
                'name' => 'Berry Soda 330ml',
                'category' => 'soft-drinks',
                'description' => 'Mixed berry flavor soda with antioxidant notes.',
                'price' => 185.00,
                'stock' => 82,
                'image' => 'images/Soft Drinks/berry-soda.png',
            ],
            [
                'id' => 20,
                'name' => 'Cola Zero Sugar 330ml',
                'category' => 'soft-drinks',
                'description' => 'Zero sugar cola with same great taste without calories.',
                'price' => 200.00,
                'stock' => 75,
                'image' => 'images/Soft Drinks/cola-zero-sugar.png',
            ],

            // Dairy Drinks - lowercase with hyphens
            [
                'id' => 21,
                'name' => 'Chocolate Milk 250ml',
                'category' => 'dairy',
                'description' => 'Rich chocolate milk with creamy texture and sweet cocoa flavor.',
                'price' => 220.00,
                'stock' => 45,
                'image' => 'images/Dairy Drinks/chocolate-milk.png',
            ],
            [
                'id' => 22,
                'name' => 'Strawberry Milk 250ml',
                'category' => 'dairy',
                'description' => 'Sweet strawberry milk with natural berry flavoring.',
                'price' => 215.00,
                'stock' => 40,
                'image' => 'images/Dairy Drinks/strawberry-milk.png',
            ],
            [
                'id' => 23,
                'name' => 'Banana Milk 250ml',
                'category' => 'dairy',
                'description' => 'Creamy banana milk with natural fruit sweetness.',
                'price' => 225.00,
                'stock' => 35,
                'image' => 'images/Dairy Drinks/banana-milk.png',
            ],
            [
                'id' => 24,
                'name' => 'Vanilla Milkshake 300ml',
                'category' => 'dairy',
                'description' => 'Smooth vanilla milkshake with rich and creamy texture.',
                'price' => 320.00,
                'stock' => 30,
                'image' => 'images/Dairy Drinks/vanilla-milkshake.png',
            ],
            [
                'id' => 25,
                'name' => 'Chocolate Milkshake 300ml',
                'category' => 'dairy',
                'description' => 'Thick chocolate milkshake with indulgent cocoa flavor.',
                'price' => 330.00,
                'stock' => 28,
                'image' => 'images/Dairy Drinks/chocolate-milkshake.png',
            ],
            [
                'id' => 26,
                'name' => 'Strawberry Milkshake 300ml',
                'category' => 'dairy',
                'description' => 'Creamy strawberry milkshake with fresh fruit notes.',
                'price' => 325.00,
                'stock' => 25,
                'image' => 'images/Dairy Drinks/strawberry-milkshake.png',
            ],
            [
                'id' => 27,
                'name' => 'Coconut Milk 250ml',
                'category' => 'dairy',
                'description' => 'Natural coconut milk with tropical creaminess.',
                'price' => 230.00,
                'stock' => 32,
                'image' => 'images/Dairy Drinks/coconut-milk.png',
            ],
            [
                'id' => 28,
                'name' => 'Almond Milk 250ml',
                'category' => 'dairy',
                'description' => 'Plant-based almond milk with nutty flavor and health benefits.',
                'price' => 240.00,
                'stock' => 35,
                'image' => 'images/Dairy Drinks/almond-milk.png',
            ],
            [
                'id' => 29,
                'name' => 'Oat Milk 250ml',
                'category' => 'dairy',
                'description' => 'Silky oat milk with mild sweetness and eco-friendly appeal.',
                'price' => 235.00,
                'stock' => 38,
                'image' => 'images/Dairy Drinks/oat-milk.png',
            ],
            [
                'id' => 30,
                'name' => 'Yogurt Drink 250ml',
                'category' => 'dairy',
                'description' => 'Probiotic yogurt drink with digestive health benefits.',
                'price' => 210.00,
                'stock' => 42,
                'image' => 'images/Dairy Drinks/yogurt-drink.png',
            ],

            // Energy Drinks - lowercase with hyphens
            [
                'id' => 31,
                'name' => 'Energy Blast 250ml',
                'category' => 'energy-drinks',
                'description' => 'High caffeine energy drink with B-vitamins and taurine.',
                'price' => 350.00,
                'stock' => 60,
                'image' => 'images/Energy Drinks/energy-blast.png',
            ],
            [
                'id' => 32,
                'name' => 'Red Bull Style 250ml',
                'category' => 'energy-drinks',
                'description' => 'Premium energy drink with classic formula and caffeine boost.',
                'price' => 360.00,
                'stock' => 55,
                'image' => 'images/Energy Drinks/red-bull-style.png',
            ],
            [
                'id' => 33,
                'name' => 'Monster Style 473ml',
                'category' => 'energy-drinks',
                'description' => 'Large format energy drink with extra caffeine and flavor.',
                'price' => 420.00,
                'stock' => 50,
                'image' => 'images/Energy Drinks/monster-style.png',
            ],
            [
                'id' => 34,
                'name' => 'Green Tea Energy 250ml',
                'category' => 'energy-drinks',
                'description' => 'Green tea based energy drink with antioxidants and natural caffeine.',
                'price' => 340.00,
                'stock' => 48,
                'image' => 'images/Energy Drinks/green-tea-energy.png',
            ],
            [
                'id' => 35,
                'name' => 'Coffee Energy 250ml',
                'category' => 'energy-drinks',
                'description' => 'Coffee based energy drink with bold flavor and sustained energy.',
                'price' => 370.00,
                'stock' => 45,
                'image' => 'images/Energy Drinks/coffee-energy.png',
            ],
            [
                'id' => 36,
                'name' => 'Berry Energy 250ml',
                'category' => 'energy-drinks',
                'description' => 'Berry flavored energy drink with antioxidant blend.',
                'price' => 355.00,
                'stock' => 52,
                'image' => 'images/Energy Drinks/berry-energy.png',
            ],
            [
                'id' => 37,
                'name' => 'Citrus Energy 250ml',
                'category' => 'energy-drinks',
                'description' => 'Citrus flavored energy drink with vitamin C and zesty taste.',
                'price' => 345.00,
                'stock' => 58,
                'image' => 'images/Energy Drinks/citrus-energy.png',
            ],
            [
                'id' => 38,
                'name' => 'Zero Sugar Energy 250ml',
                'category' => 'energy-drinks',
                'description' => 'Zero sugar energy drink with artificial sweeteners.',
                'price' => 380.00,
                'stock' => 40,
                'image' => 'images/Energy Drinks/zero-sugar-energy.png',
            ],
            [
                'id' => 39,
                'name' => 'Natural Energy 250ml',
                'category' => 'energy-drinks',
                'description' => 'Natural energy drink with plant-based ingredients.',
                'price' => 390.00,
                'stock' => 35,
                'image' => 'images/Energy Drinks/natural-energy.png',
            ],
            [
                'id' => 40,
                'name' => 'Electrolyte Energy 250ml',
                'category' => 'energy-drinks',
                'description' => 'Electrolyte enhanced energy drink for hydration and stamina.',
                'price' => 375.00,
                'stock' => 45,
                'image' => 'images/Energy Drinks/electrolyte-energy.png',
            ],
        ];

        foreach ($products as $productData) {
            $productData['created_at'] = now();
            $productData['updated_at'] = now();
            
            Product::upsert(
                $productData,
                ['id'], // unique columns
                ['name', 'category', 'description', 'price', 'stock', 'image', 'updated_at'] // columns to update
            );
        }
    }
}